version: "3.8"
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "7545:7545"
    command: [ "--host", "0.0.0.0", "--port", "7545", "--networkId", "5777", "-d" ]
    networks:
      - mynetwork

  truffle:
    build:
      context: .
      dockerfile: Dockerfile  # explicitly specify if needed
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - ganache
    command: >
      sh -c "
      until nc -z ganache 7545; do
        echo 'Waiting for ganache...';
        sleep 2;
      done;
      truffle compile &&
      truffle migrate --network development &&
      tail -f /dev/null
      "
    networks:
      - mynetwork

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - ganache
    environment:
      - NEXT_PUBLIC_GANACHE_URL=http://ganache:7545
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
